### ISSUE TITLE
data-preferred="" attribute only shows first country, doesn't match region

### ISSUE THREAD

**Issue by papagunit** [country-regions/country-region-selector#71]
I'm unable to get the data preferred attribute to work properly.

[Example here](https://cdn.rawgit.com/papagunit/49bdf3eaa72d34ef95368757ba661b63/raw/8bbac244789c1226fb869e7519807f775278716d/country%20region%20example.html)

Please advise. Thanks!

**Comment by benkeen** [comment]
Hey @papagunit, sorry about that - I'll flag this as a bug, but not for the obvious reason! 

Try this instead:

```html
<select placeholder="Your Country" class="crs-country" data-preferred="US,GB,CA" data-region-id="regiondrop"></select>
<select placeholder="Your State/Region" id="regiondrop"></select>
```

UK's short code is actually "GB" (Great Britain) - it seems to work fine once that's fixed. But the bug is the awful error handling...! I'll patch this in the next release.

Thanks @papagunit :)

**Comment by papagunit** [comment]
Turns out the bug was between the chair and the keyboard.

Thanks!
